### ISSUE TITLE
Can't open video

### ISSUE THREAD

**Issue by Pemicope** [otsaloma/gaupol#87] opened 2018-04-27 16:54 UTC
Hello, I'm having a problem with Gaupol.
Everything works fine except one thing; when I try to open a video file I get the following error:

Traceback

File: /usr/share/gaupol/gaupol/agents/video.py
Line: 198
In: _on_load_video_activate

    self.load_video(path)

File: /usr/share/gaupol/gaupol/agents/video.py
Line: 161
In: load_video

    self._init_player_widgets()

File: /usr/share/gaupol/gaupol/agents/video.py
Line: 129
In: _init_player_widgets

    self.player = gaupol.VideoPlayer()

File: /usr/share/gaupol/gaupol/player.py
Line: 74
In: __init__

    self._init_pipeline()

File: /usr/share/gaupol/gaupol/player.py
Line: 162
In: _init_pipeline

    self.widget.pack_start(sink.props.widget, True, True, 0)

AttributeError: 'NoneType' object has no attribute 'props'

Environment

Platform: Linux-4.15.0-20-generic-x86_64-with-Ubuntu-18.04-bionic
Locale: pt_PT.utf_8

Versions

aeidon: 1.3.1
chardet: 3.0.4
enchant: 2.0.0
gaupol: 1.3.1
gstreamer: 1.14.0.0
gtk+: 3.22.30
pygobject: 3.26.1
python: 3.6.5

I'm using Ubuntu Budgie 18.04 at the moment, but I've tried it on Ubuntu 18.04 and Kubuntu 18.04 with the same results. Do I need to install any other dependency, or is it something else?

Thank you!

**Comment by otsaloma** [comment] 2018-04-27 19:04
Duplicate of #83

TL/DR: Install "gstreamer1.0-gtk3".

**Comment by otsaloma** [comment] 2018-04-27 20:33
> I've installed "gstreamer1.0-gtk3" and at first it seems the problem is fixed, but it's not. The video now opens but it doesn't play. I only see a black picture and no sound...

Did you install via Ubuntu's package management? Do you have all the dependencies installed, including "recommends"?

https://packages.ubuntu.com/bionic/gaupol

**Comment by Pemicope** [comment] 2018-04-27 20:55
Thank you for your reply!
I've installed "gstreamer1.0-gtk3" from the command line. I've tried to install every dependency from https://packages.ubuntu.com/bionic/gaupol but it says it's already the latest version.

When I open Gaupol from the command line and open a video I get this message: "mesa: for the -simplifycfg-sink-common option: may only occur zero or one times!"

I open this helps. Thank you!

**Comment by otsaloma** [comment] 2018-04-27 21:02
Do you have "gstreamer1.0-vaapi" installed? Could you uninstall that and try again?

https://bugs.launchpad.net/ubuntu/+source/gstreamer-vaapi/+bug/1720820

**Comment by Pemicope** [comment] 2018-04-27 21:25
Yes, I have it installed. It's the latest version...
Thank you!

**Comment by Pemicope** [comment] 2018-04-27 21:52
I think I might have found the problem. I don't know much about this but I think the problem is in the video card. I've been testing Gaupol on a laptop with an AMD card but just now I tried it on a desktop with an Nvidia card and after installing "gstreamer1.0-gtk3" it just worked! I'm fine with it, I only use the laptop for testing.

Thank you so much for your help!

**Comment by otsaloma** [comment] 2018-04-27 22:05
Yes, on some video cards gstreamer1.0-vaapi seems to cause trouble, it's an easy fix to just remove it.

**Closed by otsaloma** 2018-04-27 22:05 UTC

**Comment by Pemicope** [comment] 2018-04-27 22:16
Oh, I see. Thank you!

**Comment by jevillate** [comment] 2018-05-04 19:27
Yes, installing gstreamer1.0-gtk3 and uninstalling gstreamer1.0-vappi fixed the problem for me, in Ubuntu 18.04, and gaupol now works fine as it did in Ubuntu 17.10. Thanks otsaloma.

**Comment by solfas** [comment] 2022-03-21 20:03
For me only this helped:

sudo apt install gstreamer1.0-x

Source: https://www.antixforum.com/forums/topic/problems-while-starting-to-use-video-subtiteling-software-gaupol/
