### ISSUE TITLE
Gaupol crashed trying to load a video on Ubuntu 17.10

### ISSUE THREAD

**Issue by revenger98** [otsaloma/gaupol#69] opened 2017-11-10 21:58 UTC
Traceback

File: /usr/share/gaupol/gaupol/agents/video.py
Line: 184
In: _on_load_video_activate

    self.player.set_path(path)

File: /usr/share/gaupol/gaupol/player.py
Line: 331
In: set_path

    self.set_uri(aeidon.util.path_to_uri(path))

File: /usr/share/gaupol/gaupol/player.py
Line: 340
In: set_uri

    self._xid = self.widget.get_window().get_xid()

AttributeError: 'GdkWaylandWindow' object has no attribute 'get_xid'

Environment

Platform: Linux-4.13.0-16-generic-x86_64-with-Ubuntu-17.10-artful
Locale: en_US.utf_8

Versions

aeidon: 1.2
chardet: 3.0.4
enchant: 1.6.7
gaupol: 1.2
gstreamer: 1.12.3.0
gtk+: 3.22.24
pygobject: 3.24.1
python: 3.6.3

**Comment by otsaloma** [comment] 2017-11-10 22:39
Duplicate of #60

**Closed by otsaloma** 2017-11-10 22:39 UTC
