### ISSUE TITLE
Can't load any Videos

### ISSUE THREAD

**Issue by HelySaul** [otsaloma/gaupol#44] opened 2017-03-14 18:20 UTC
I'm trying to load a video but it can't be done in Windows... The fields and buttons are disabled.
![2017-03-14](https://cloud.githubusercontent.com/assets/17388459/23916044/431ea5b4-08c1-11e7-9caa-acf4486093ad.png)

**Comment by otsaloma** [comment] 2017-03-14 19:06
Duplicate of #27.

**Closed by otsaloma** 2017-03-14 19:06 UTC
