### ISSUE TITLE
Gaupol should accept audio files same as video files

### ISSUE THREAD

**Issue by HalvorRaknes** [otsaloma/gaupol#215] opened 2024-02-01 12:54 UTC
Since subtitles can be added to audio files same as video files Gaupol shouldn't reject e.g. mp3 files when they are given as video source.

Now I have to convert a copy of the audio file to a video format so that the program will read it.

**Comment by otsaloma** [comment] 2024-02-01 21:17
Duplicate of #198

**Closed by otsaloma** 2024-02-01 21:17 UTC
