### ISSUE TITLE
Gaupol 1.3.1 message (something went wrong etc.) when trying to load video file

### ISSUE THREAD

**Issue by halaronio** [otsaloma/gaupol#110] opened 2018-10-05 08:02 UTC
Hi. After upgrading from Ubuntu 16.04 to Ubuntu 18.04 (not fresh installation), when I try to load a video file (of any type, .avi, .mp4, .mkv etc.) I get the message "Something went wrong. You have probably discovered a bug. Please report it etc etc".
Thanks.

[gaupol.log](https://github.com/otsaloma/gaupol/files/2449129/gaupol.log)

**Comment by otsaloma** [comment] 2018-10-05 15:06
Duplicate of #83

TL/DR: Install "gstreamer1.0-gtk3".

**Closed by otsaloma** 2018-10-05 15:06 UTC
