### ISSUE TITLE
playbin.query_position fails

### ISSUE THREAD

**Issue by rffontenelle** [otsaloma/gaupol#78] opened 2018-02-07 17:22 UTC
I was subtitling at the moment, with video open, and I'm not sure whether was writer in a entry or just pressed "j" to add a new entry, when a popup with the following message showed up.

```
Traceback

File: /usr/lib/python3.6/site-packages/gaupol/agents/edit.py
Line: 150
In: _on_insert_subtitle_at_video_position_activate

    index = bisect.bisect_right(starts, pos)

TypeError: '<' not supported between instances of 'NoneType' and 'float'

Environment

Platform: Linux-4.14.15-1-ARCH-x86_64-with-arch
Locale: pt_BR.utf_8

Versions

aeidon: 1.2
chardet: 3.0.4
enchant: 2.0.0
gaupol: 1.2
gstreamer: 1.12.4.0
gtk+: 3.22.26
pygobject: 3.26.1
python: 3.6.4
```

P.s.: The installed enchant version is actually 2.2.1

**Comment by rffontenelle** [comment] 2018-02-07 17:26
I initially thought it crashed, but it seems that it didn't and I'm still using it without having to close it.

**Comment by otsaloma** [comment] 2018-02-07 20:30
It seems that querying position from GStreamer fails (`playbin.query_position`). That's where the `None` comes from. There's another issue where the same thing failed in a different context: https://github.com/otsaloma/gaupol/issues/67

So, this does look like a bug, but I can't tell under what conditions it happens, can't reproduce it and don't really what do in such a case. Suggestions are welcome.

**Comment by rffontenelle** [comment] 2018-02-08 11:24
Fair enough. I'll try to reproduce it somehow and let you know.

**Comment by otsaloma** [comment] 2018-05-28 20:12
I suspect the problem is due to some kind of a temporary pipeline state or state change and if the query is not succesful, it's worth waiting a tiny amount and trying again. I added such a fix in the above commit. I also added some checks against the `None` value, so if the root problem persists, you shouldn't get an error anymore, but whatever ongoing action will silently fail. I keep this issue open for now, close it later if the problem has indeed been solved.

**Closed** 2018-07-07 15:59 UTC
