### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nadieenespecial** [otsaloma/gaupol#107] opened 2018-09-06 11:50 UTC
Hi, I tried to load an mkv (Matroska video - video/x-matroska) after a srt

```
Traceback

File: /usr/share/gaupol/gaupol/agents/video.py
Line: 198
In: _on_load_video_activate

    self.load_video(path)

File: /usr/share/gaupol/gaupol/agents/video.py
Line: 161
In: load_video

    self._init_player_widgets()

File: /usr/share/gaupol/gaupol/agents/video.py
Line: 129
In: _init_player_widgets

    self.player = gaupol.VideoPlayer()

File: /usr/share/gaupol/gaupol/player.py
Line: 74
In: __init__

    self._init_pipeline()

File: /usr/share/gaupol/gaupol/player.py
Line: 162
In: _init_pipeline

    self.widget.pack_start(sink.props.widget, True, True, 0)

AttributeError: 'NoneType' object has no attribute 'props'

Environment

Platform: Linux-4.15.0-33-generic-x86_64-with-Ubuntu-18.04-bionic
Locale: en_US.utf_8

Versions

aeidon: 1.3.1
chardet: 3.0.4
enchant: 2.0.0
gaupol: 1.3.1
gstreamer: 1.14.1.0
gtk+: 3.22.30
pygobject: 3.26.1
python: 3.6.5
```

![screenshot from 2018-09-06 08-48-21](https://user-images.githubusercontent.com/43034851/45155529-b0e62280-b1b1-11e8-9c62-56c626e2c7d6.png)

**Comment by otsaloma** [comment] 2018-09-06 14:56
Duplicate of #83

TL/DR: Install "gstreamer1.0-gtk3".

**Closed by otsaloma** 2018-09-06 14:56 UTC
