### ISSUE TITLE
Error after clicking inside a highlighted text column 

### ISSUE THREAD

**Issue by iSimorgh** [otsaloma/gaupol#172] opened 2020-11-22 22:50 UTC
This is the error message when double clicking or clicking inside a highlighted text column:

Traceback

TypeError: Couldn't find foreign struct converter for 'cairo.Context'

Environment

Platform: Linux-5.3.18-lp152.50-default-x86_64-with-glibc2.3.4
Locale: en_US.utf_8

Versions

aeidon: 1.8
chardet: 3.0.4
gaupol: 1.8
gspell: 1
gstreamer: 1.16.2.0
gtk+: 3.24.20
pygobject: 3.34.0
python: 3.6.10

is there something wrong with my installation? I have even tried to uninstall and install the program.

**Comment by otsaloma** [comment] 2020-11-22 23:04
Duplicate of #80 

You need python-cairo, or whatever it's called in openSUSE. You might also want to file a bug report against the openSUSE package, as this looks like a missing dependency there.

**Closed by otsaloma** 2020-11-22 23:04 UTC
