### ISSUE TITLE
error loading video - bug

### ISSUE THREAD

**Issue by robertfrazer** [otsaloma/gaupol#98] opened 2018-07-08 13:36 UTC
File: /usr/share/gaupol/gaupol/agents/video.py
Line: 198
In: _on_load_video_activate

    self.load_video(path)

File: /usr/share/gaupol/gaupol/agents/video.py
Line: 161
In: load_video

    self._init_player_widgets()

File: /usr/share/gaupol/gaupol/agents/video.py
Line: 129
In: _init_player_widgets

    self.player = gaupol.VideoPlayer()

File: /usr/share/gaupol/gaupol/player.py
Line: 74
In: __init__

    self._init_pipeline()

**Comment by otsaloma** [comment] 2018-07-08 17:12
This is not the full traceback, but likely it's a duplicate of #83.

TL/DR: Install "gstreamer1.0-gtk3".

**Closed by otsaloma** 2018-07-08 17:12 UTC
