### ISSUE TITLE
'GdkWaylandWindow' object has no attribute 'get_xid'

### ISSUE THREAD

**Issue by 0xfinch** [otsaloma/gaupol#64] opened 2017-09-21 17:39 UTC
I work on a GNOME+Wayland environment.
An error dialogue showed up after I selected a file to work (webm format). 
I was trying to load the video (Video -> Load Video ) and the following error appeared. 

```
Traceback

File: /usr/lib/python3.6/site-packages/gaupol/agents/video.py
Line: 184
In: _on_load_video_activate

    self.player.set_path(path)

File: /usr/lib/python3.6/site-packages/gaupol/player.py
Line: 331
In: set_path

    self.set_uri(aeidon.util.path_to_uri(path))

File: /usr/lib/python3.6/site-packages/gaupol/player.py
Line: 340
In: set_uri

    self._xid = self.widget.get_window().get_xid()

AttributeError: 'GdkWaylandWindow' object has no attribute 'get_xid'

Versions

aeidon: 1.0
chardet: 2.3.0
enchant: 1.6.10
gaupol: 1.0
gstreamer: 1.12.2.0
gtk+: 3.22.19
pygobject: 3.24.1
python: 3.6.2
```

**Comment by otsaloma** [comment] 2017-09-21 19:20
Duplicate of #60

**Closed by otsaloma** 2017-09-21 19:20 UTC
